
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
data:
  config.yml: |
    ---
    server:
    type: simple
    applicationContextPath: /
    adminContextPath: /admin

    content: Stranger

    logging:
    level: INFO
