name: Pulumi
on:
  pull_request:
    paths: [ 'infra/**' ]
jobs:
  preview:
    name: Pulumi preview
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - run: npm install
      working-directory: infra

    - name: Pulumi preview
      uses: pulumi/actions@v6
      with:
        work-dir: infra
        command: preview
        stack-name: dev
        comment-on-pr: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
