name: terraform-plan
on:
  pull_request:
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
    - uses: ahmadnassri/action-terraform-report@v4
      with:
        terraform-text: ${{ github.workspace }}/tf-plan.text
        terraform-json: ${{ github.workspace }}/tf-plan.json
        remove-stale-reports: true
